local ra = resource.AddFile
	ra 'sound/effects/hit.wav'
	ra 'sound/effects/exp.wav'
	ra 'sound/effects/lvl.wav'
	ra 'sound/effects/marker.wav'
	ra 'sound/effects/distant/pist_heavy.mp3'
	ra 'sound/effects/distant/pist_light.mp3'
	ra 'sound/effects/distant/sniper_heavy.mp3'
	ra 'sound/effects/distant/sniper_light.mp3'
	ra 'sound/effects/distant/rifle.mp3'
	ra 'sound/effects/distant/shotgun.mp3'
	
	ra 'sound/suit/death.mp3'
	ra 'sound/suit/energy.mp3'
	ra 'sound/suit/attach.wav'
	ra 'sound/suit/detach.wav'
	ra 'sound/suit/sights_off.wav'
	ra 'sound/suit/sights_on.wav'
	ra 'sound/suit/switch.wav'
	
	ra 'ambient/ambience/rainscapes/crucial_waterrain_light_loop.wav'
	ra 'ambient/ambience/rainscapes/interior_rain_med_loop.wav'
	ra 'ambient/ambience/rainscapes/thunder_close01.wav'
	ra 'ambient/ambience/rainscapes/thunder_close02.wav'
	ra 'ambient/ambience/rainscapes/thunder_close03.wav'
	ra 'ambient/ambience/rainscapes/thunder_close04.wav'
	
	ra 'sound/weapons/357_shot.wav'
	ra 'sound/weapons/ak74_shot.wav'
	ra 'sound/weapons/awm_shot.wav'
	ra 'sound/weapons/blowtorch.wav'
	ra 'sound/weapons/crossbow_empty.wav'
	ra 'sound/weapons/crossbow_shot.wav'
	ra 'sound/weapons/discharge.wav'
	ra 'sound/weapons/draw.wav'
	ra 'sound/weapons/frag_pin.wav'
	ra 'sound/weapons/frag_throw.wav'
	ra 'sound/weapons/holster.wav'
	ra 'sound/weapons/launcher.wav'
	ra 'sound/weapons/m16_shot.wav'
	ra 'sound/weapons/m249_shot.wav'
	ra 'sound/weapons/match_reload.wav'
	ra 'sound/weapons/match_shot.wav'
	ra 'sound/weapons/mp7_shot.wav'
	ra 'sound/weapons/pist_silent.wav'
	ra 'sound/weapons/rifle_clipin.wav'
	ra 'sound/weapons/rifle_cliplock.wav'
	ra 'sound/weapons/rifle_clipout.wav'
	ra 'sound/weapons/rifle_pull.wav'
	ra 'sound/weapons/rifle_release.wav'
	ra 'sound/weapons/rifle_silent.wav'
	ra 'sound/weapons/scar_shot.wav'
	ra 'sound/weapons/sentry.wav'
	ra 'sound/weapons/sniper_silent.wav'
	ra 'sound/weapons/shotgun_silent.wav'
	ra 'sound/weapons/spas_insertshell.wav'
	ra 'sound/weapons/spas_pump.wav'
	ra 'sound/weapons/spas_shot.wav'
	ra 'sound/weapons/smg_silent.mp3'
	ra 'sound/weapons/p220_shot.wav'
	ra 'sound/weapons/toolgun.wav'
	
	ra 'sound/friday13/down.mp3'
	ra 'sound/friday13/idle.mp3'
	ra 'sound/friday13/rage.mp3'
	ra 'sound/friday13/start.mp3'
	ra 'sound/ttt/horor.mp3'
	
	ra 'materials/models/weapons/v_chainsaw/chainsaw.vmt'
	ra 'materials/models/weapons/v_chainsaw/chainsaw_chain.vmt'
	ra 'models/weapons/melee/v_chainsaw.mdl'
	ra 'models/weapons/melee/w_chainsaw.mdl'
	
	ra 'models/weapons/v_match2.mdl'
	ra 'models/weapons/v_scopebow.mdl'
	
	ra 'models/attachments/kascope.mdl'
	ra 'models/attachments/suppressor.mdl'
	ra 'models/bunneh/scope01.mdl'
	ra 'models/wystan/attachments/2cog.mdl'
	ra 'models/wystan/attachments/2octorrds.mdl'
	ra 'models/wystan/attachments/2otech557sight.mdl'
	
	ra 'materials/effects/lensflare/bar.vmt'
	ra 'materials/effects/lensflare/color_ring.vmt'
	ra 'materials/effects/lensflare/flare.vmt'
	ra 'materials/effects/lensflare/iris.vmt'
	ra 'materials/effects/dot.vmt'
	ra 'materials/effects/laser.vmt'
	ra 'materials/effects/reflex.vmt'
	ra 'materials/trails/smoke.vmt'
	
	ra 'materials/models/weapons/v_crossbow/lance.vmt'
	ra 'materials/models/weapons/v_crossbow/lense.vmt'
	
	ra 'materials/models/attachments/suppressor/silincer.vmt'
	ra 'materials/models/bunneh/scope.vmt'
	
	ra 'materials/models/blacktea/attachments/aim2.vmt'
	ra 'materials/models/blacktea/attachments/kascope08_d.vmt'
	ra 'materials/models/blacktea/attachments/kascope08_n.vmt'
	
	ra 'materials/gaben.png'	
	ra 'materials/overlay/neardeath.png'
	ra 'materials/overlay/binocular.png'
	
	ra 'materials/models/v_models/weapons/m60/m60.vmt'
	ra 'models/v_models/v_m60.mdl'
	ra 'models/w_models/weapons/w_m60.mdl'
	
	ra 'materials/models/v_models/weapons/smg/uzi_world.vmt'
	ra 'materials/models/v_models/weapons/smg/uzi.vmt'
	ra 'models/v_models/v_smg.mdl'
	ra 'models/w_models/weapons/w_smg_uzi.mdl'
	
	ra 'materials/models/v_models/weapons/eq_defibrillator/defibrillator.vmt'
	ra 'materials/models/v_models/weapons/eq_defibrillator/v_eq_defibrillator.vmt'
	ra 'models/v_models/v_defibrillator.mdl'
	ra 'models/w_models/weapons/w_eq_defibrillator_paddles.mdl'
	
	ra 'models/v_models/v_grenade_launcher.mdl'
	ra 'models/w_models/weapons/w_grenade_launcher.mdl'
	ra 'models/w_models/weapons/w_he_grenade.mdl'
	
	ra 'models/props/cs_militia/circularsaw01.mdl'
	
	ra 'materials/models/v_models/weapons/rifle/ak47.vmt'
	ra 'materials/models/v_models/weapons/rifle/m16a2.vmt'
	ra 'materials/models/v_models/weapons/rifle/m16a2_world.vmt'
	ra 'materials/models/v_models/weapons/rifle/rifle_b.vmt'
	ra 'materials/models/v_models/weapons/grenade_launcher/grenade_launcher.vmt'
	ra 'materials/models/weapons/w_he_grenade/w_he_grenade.vmt'
	ra 'materials/models/props/cs_militia/circularsaw01.vmt'
	ra 'materials/models/props/cs_militia/circularsawblade01.vmt'
	
	ra 'models/v_models/v_desert_rifle.mdl'
	ra 'models/w_models/weapons/w_desert_rifle.mdl'
	
	ra 'models/v_models/v_rifle_ak47.mdl'
	ra 'models/w_models/weapons/w_rifle_ak47.mdl'
	
	ra 'models/v_models/v_rifle.mdl'
	ra 'models/w_models/weapons/w_rifle_m16a2.mdl'
	
	ra 'resource/csd.ttf'
	